### ISSUE TITLE
Calling Song.lyrics results in KeyError: 'lyrics-body-text'

### ISSUE THREAD

**Issue by danielnjoo** [brenns10/tswift#8]
Hi! Awesome repo:)

Accessing lyrics as in the examples works fine. However, when I try to programmatically create instances of Song, then print their lyrics. I run into the following error:

```
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/lxml/html/__init__.py", line 409, in get_element_by_id
    return _id_xpath(self, id=id)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "billboard.py", line 50, in <module>
    print(s.lyrics)
  File "/anaconda/lib/python3.6/site-packages/tswift.py", line 76, in lyrics
    self.load()
  File "/anaconda/lib/python3.6/site-packages/tswift.py", line 68, in load
    lyric_div = tree.get_element_by_id('lyrics-body-text')
  File "/anaconda/lib/python3.6/site-packages/lxml/html/__init__.py", line 414, in get_element_by_id
    raise KeyError(id)
KeyError: 'lyrics-body-text'
```

This occurs when I do:

```
import tswift as tw
for index, row in cleaned.iterrows():
    s=tw.Song(row['song'],row['artist'])
    print(s.lyrics) 
```

Don't get an issue when I try `print(s)`, which results in 

Song(title='Rockstar', artist='Post Malone Featuring 21 Savage')
Song(title='Too Good At Goodbyes', artist='Sam Smith')
Song(title='I Fall Apart', artist='Post Malone')
Song(title='Gucci Gang', artist='Lil Pump')

Thanks for any assistance, perhaps you know what's going on:)

**Comment by brenns10** [comment]
The song title and artist goes directly into the URL which gets requested from Metrolyrics. For your first song, the URL is:

http://www.metrolyrics.com/rockstar-lyrics-post-malone-featuring-21-savage.html

If you click it, you'll notice that doesn't exist. Looks like the correct link is:

http://www.metrolyrics.com/rockstar-lyrics-post-malone.html

So, if you constructed the first song like this:

```python
s = Song(title='Rockstar', artist='Post Malone')
```

Everything would work fine (looks like the remaining songs do exist). I wish there was a good way to know how Metrolyrics decides what exact title and artist to use, but unfortunately they don't tell us.

**Comment by danielnjoo** [comment]
I used a try/catch block. Do you have any better suggestions? Also on how best to conform to metrolyric standards: removing any Featured... or Ft., etc.? 

```
for index, row in cleaned.iterrows():
    print('trying to print lyrics for: ',row['song'],row['artist'])
    try:
        temp=(tw.Song(row['song'],row['artist']).lyrics)
        ## store temp somewhere
        print('success\n')
    except:
        print('error\n')
```

Thanks!

**Comment by brenns10** [comment]
I don't have a suggestion for knowing exactly how Metrolyrics decides to encode artists - I'm an outsider and have no more information than you do.

However, you don't *have* to know the exact encoding to find the song. This package actually has a Google feature that allows you to find the first Metrolyrics result by searching for the song on Google. For example, you could do this:

```python
for index, row in cleaned.iterrows():
    print('trying to print lyrics for: ',row['song'],row['artist'])
    try:
        temp=(tw.Song(row['song'],row['artist']).lyrics)
        ## store temp somewhere
        print('success\n')
    except:
        song = tw.Song.find_song(row['song'] + ' ' + row['artist'])
        if song:
            ## store temp somewhere
            print('success')
        else:
            print('error\n')
```

This isn't 100% foolproof but it does a pretty good job of doing what you mean. Hope this helps :)
